/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author btooo
 */
public class BinhLuanGopYChungCu extends javax.swing.JFrame {

    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DB db;
    DBCollection user;
    DBCollection title;
    DBCollection comment;
    DefaultTableModel tblModel;
    
    public BinhLuanGopYChungCu() {
        initComponents();
        datformvitrigiua();
        banguser();
        KetNoiMongoDBBangUser();
        KetNoiMongoDBBangTitle();
        KetNoiMongoDBBangComment();
        LayDuLieu();
        DuaDuLieuVaoCombobox();
    }
    
    public void datformvitrigiua(){
        this.setTitle("Quản lý bình luận chung cư");
        int w = this.getWidth();
        int h = this.getHeight();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(
                (screenSize.width/2)-(w/2),
                ((screenSize.height/2)-(h/2)),w,h);
    }
    
    public void banguser(){
        tblTitle.add("Object id"); tblTitle.add("Name");
        tblUser.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    
    public void KetNoiMongoDBBangUser(){
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            db = mongo.getDB("BINHLUANGOPYCHUNGCU");
            user = db.getCollection("User");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void KetNoiMongoDBBangTitle(){
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            db = mongo.getDB("BINHLUANGOPYCHUNGCU");
            title = db.getCollection("Title");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void KetNoiMongoDBBangComment(){
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            db = mongo.getDB("BINHLUANGOPYCHUNGCU");
            comment = db.getCollection("Comment");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void LayDuLieu(){
        DBCursor cursor = user.find();
        while(cursor.hasNext()){
            DBObject doc = cursor.next();
            Object _id = doc.get("_id");
            String name = doc.get("name").toString();
            Vector v = new Vector();
            v.add(_id); v.add(name);
            tblData.add(v);
            tblUser.setModel(new DefaultTableModel(tblData, tblTitle));
        }
    }

    public void DuaDuLieuVaoCombobox(){
        DBCursor cursor = title.find();
        while(cursor.hasNext()){
            DBObject doc = cursor.next();
            String nametitle = doc.get("nametitle").toString().trim();
            cbboxTieuDe.addItem(nametitle);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnThemTieuDe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        btnThemUser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBinhLuan = new javax.swing.JTextField();
        btnThemBinhLuan = new javax.swing.JButton();
        txtTieuDe = new javax.swing.JTextField();
        cbboxTieuDe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtComment.setColumns(20);
        txtComment.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtComment.setRows(5);
        txtComment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(txtComment);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tạo tiêu đề:");

        btnThemTieuDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemTieuDe.setText("Thêm");
        btnThemTieuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTieuDeActionPerformed(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tiêu đề:");

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnThemUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemUser.setText("Thêm user");
        btnThemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemUserActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Bình luận:");

        txtBinhLuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnThemBinhLuan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemBinhLuan.setText("Thêm bình luận");
        btnThemBinhLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBinhLuanActionPerformed(evt);
            }
        });

        txtTieuDe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbboxTieuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbboxTieuDeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên tài khoản:");

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                        .addComponent(txtBinhLuan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbboxTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, 0, 210, Short.MAX_VALUE)
                                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnThemBinhLuan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbboxTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtBinhLuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnThemBinhLuan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void XoaDuLieu(){
        tblModel = (DefaultTableModel) tblUser.getModel();
        tblModel.setRowCount(0);
    }
    
    private void btnThemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemUserActionPerformed
        if(txtTaiKhoan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tài khoản để thêm user", "Thông báo", 2);
            return;
        }
        
        BasicDBObject doc = new BasicDBObject();
        doc.put("name", txtTaiKhoan.getText().trim());
        
        user.insert(doc);
        txtTaiKhoan.setText("");
        XoaDuLieu();
        LayDuLieu();
    }//GEN-LAST:event_btnThemUserActionPerformed

    private void btnThemTieuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTieuDeActionPerformed
        if(txtTieuDe.getText().equals("") || txtTaiKhoan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tài khoản và tiêu đề để thêm bài bình luận", "Thông báo", 2);
            return;
        }
        
        BasicDBObject doc = new BasicDBObject();
        doc.put("nametitle", txtTieuDe.getText().trim());
        doc.put("name", txtTaiKhoan.getText().trim());
        title.insert(doc);
        cbboxTieuDe.addItem(txtTieuDe.getText().trim());
        txtTaiKhoan.setText("");
        txtTieuDe.setText("");
    }//GEN-LAST:event_btnThemTieuDeActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        int i = tblUser.getSelectedRow();
        txtTaiKhoan.setText(tblUser.getValueAt(i, 1).toString().trim());
        txtTaiKhoan.setEnabled(false);
        btnThemUser.setEnabled(false);
    }//GEN-LAST:event_tblUserMouseClicked
    
    private void btnThemBinhLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBinhLuanActionPerformed
        if(cbboxTieuDe.getSelectedIndex() < 0|| txtTaiKhoan.getText().equals("") || txtBinhLuan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên tài khoản, bình luận và chọn tiêu đề để thêm bài bình luận", "Thông báo", 2);
            return;
        }
        BasicDBObject doc = new BasicDBObject();
        doc.put("nametitle", cbboxTieuDe.getSelectedItem().toString().trim());
        doc.put("name", txtTaiKhoan.getText().trim());
        doc.put("comment", txtBinhLuan.getText().trim());
        comment.insert(doc);
        String str = "Name: " + txtTaiKhoan.getText().trim() + "\nComment: " + txtComment.getText().trim() + "\n\n";
        txtComment.setText(txtComment.getText() + "Name: " + txtTaiKhoan.getText().trim() + "\nComment: " + txtBinhLuan.getText().trim() + "\n\n");
        txtTaiKhoan.setText("");
        txtBinhLuan.setText("");
    }//GEN-LAST:event_btnThemBinhLuanActionPerformed

    public String LayCommentTheoTieuDe(){
        String str = "";
        BasicDBObject Query = new BasicDBObject();
        Query.put("nametitle", cbboxTieuDe.getSelectedItem().toString().trim());
        DBCursor cursor = comment.find(Query);
        while(cursor.hasNext()){
            DBObject doc = cursor.next();
            String name = doc.get("name").toString();
            String comment = doc.get("comment").toString();
            str += "Name: " + name + "\nComment: " + comment + "\n\n";
        }
        return str;
    }
    
    private void cbboxTieuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbboxTieuDeActionPerformed
        txtComment.setText("");
        txtComment.setText(LayCommentTheoTieuDe());
    }//GEN-LAST:event_cbboxTieuDeActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        tblUser.setModel(new DefaultTableModel(tblData, tblTitle));
        txtTaiKhoan.setText("");
        txtTaiKhoan.setEnabled(true);
        btnThemUser.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BinhLuanGopYChungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BinhLuanGopYChungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BinhLuanGopYChungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BinhLuanGopYChungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BinhLuanGopYChungCu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemBinhLuan;
    private javax.swing.JButton btnThemTieuDe;
    private javax.swing.JButton btnThemUser;
    private javax.swing.JComboBox<String> cbboxTieuDe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtBinhLuan;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTieuDe;
    // End of variables declaration//GEN-END:variables
}
